# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2

default: &default
  docker:
    - image: circleci/ruby:2.5.0-node
      environment:
        PGHOST: 127.0.0.1
        PGUSER: ubuntu
        RAILS_ENV: test
    - image: circleci/postgres:10-alpine
      environment:
        POSTGRES_USER: ubuntu
        POSTGRES_DB: chatwork_mention_task_test
    - image: memcached:1.5-alpine
  working_directory: ~/app

jobs:
  checkout_code:
    <<: *default

    steps:
      - checkout
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/app

  bundle_dependencies:
    <<: *default

    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          keys:
            - v1-bundle-{{ .Environment.CIRCLE_BRANCH }}
            - v1-bundle-master
      - run: ./.circleci/bundle_install.sh
      - save_cache:
          key: v1-bundle-{{ .Environment.CIRCLE_BRANCH }}
          paths:
            - ~/app/vendor/bundle

  rspec:
    <<: *default

    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-bundle-{{ .Environment.CIRCLE_BRANCH }}

      - run: ./.circleci/bundle_install.sh

      - run:
          name: install dockerize
          command: wget https://github.com/jwilder/dockerize/releases/download/$DOCKERIZE_VERSION/dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && tar -C /usr/local/bin -xzvf dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz && rm dockerize-linux-amd64-$DOCKERIZE_VERSION.tar.gz
          environment:
            DOCKERIZE_VERSION: v0.3.0
      - run:
          name: Wait for db
          command: dockerize -wait tcp://localhost:5432 -timeout 1m

      # Database setup
      - run: ./bin/rails db:create
      - run: ./bin/rails db:schema:load

      - run: bundle exec rspec

  rubocop:
    <<: *default

    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: v1-bundle-{{ .Environment.CIRCLE_BRANCH }}
      - run: ./.circleci/bundle_install.sh
      - run: bundle exec rubocop

  deploy:
    <<: *default

    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - run: .circleci/heroku_setup.sh
      - add_ssh_keys:
          fingerprints:
            - "e6:7a:84:ef:06:e7:14:c0:09:4c:52:68:57:de:59:7f"
      - run: .circleci/heroku_deploy.sh

workflows:
  version: 2

  build-and-deploy:
    jobs:
      - checkout_code
      - bundle_dependencies:
          requires:
            - checkout_code
      - rspec:
          requires:
            - bundle_dependencies
      - rubocop:
          requires:
            - bundle_dependencies
      - deploy:
          requires:
            - rspec
            - rubocop
          filters:
            branches:
              only: master
