default:
  servers:
    - "<%= ENV.fetch('MEMCACHED_HOST', 'localhost') %>:11211"
  options:
    namespace: "chatwork_mention_task"
    compress: true
    expires_in: <%= 30.minutes %>
    pool_size: 5
  session:
    expire_after: <%= 30.minutes %>

production:
  servers: <%= ENV["MEMCACHEDCLOUD_SERVERS"]&.split(",") %>
  options:
    expires_in: <%= 7.day %>
    username: <%= ENV["MEMCACHEDCLOUD_USERNAME"] %>
    password: <%= ENV["MEMCACHEDCLOUD_PASSWORD"] %>
  session:
    expire_after: <%= 7.day %>
